### ISSUE TITLE
Cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by tracend** [makesites/drone#27]
Ocassionally this error appears and the server had to restart

```
/local/drone/node_modules/http-proxy/lib/http-proxy/common.js:78
  var res = req.headers.host.match(/:(\d+)/);
                             ^
TypeError: Cannot call method 'match' of undefined
    at Object.common.getPort (/local/drone/node_modules/http-proxy/lib/http-proxy/common.js:78:30)
    at Array.XHeaders [as 2] (/local/drone/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:68:21)
    at ProxyServer.<anonymous> (/local/drone/node_modules/http-proxy/lib/http-proxy/index.js:83:21)
    at Server.proxyToRouter (/local/drone/lib/proxy.js:39:8)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)
```

**Comment by tracend** [comment]
Closing as addressed, as of [v0.9.0](https://github.com/makesites/drone/releases/tag/0.9.0)
